[package]
name = "dem"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = "4.5.34"
colorgrad = "0.7.0"
show-image = "0.14.1"
image = "0.25.6"
walkdir = "2.5.0"
chrono = { version = "0.4", features = ["serde"] }
